export const styles = {
  container: {
    minHeight: "100vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    background: "linear-gradient(135deg, #e0f2f1, #f1f8e9)",
    padding: "20px",
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
  },
  box: {
    backgroundColor: "#ffffff",
    borderRadius: "12px",
    padding: "40px 50px",
    boxShadow: "0 8px 16px rgba(0,0,0,0.1)",
    maxWidth: "750px",
    width: "100%",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  label: {
    fontWeight: "600",
    marginBottom: "6px",
    fontSize: "1rem",
    color: "#2f4f4f",
    userSelect: "none",
  },
  input: {
    padding: "12px 15px",
    fontSize: "1rem",
    borderRadius: "8px",
    border: "1.5px solid #9e9e9e",
    transition: "border-color 0.3s ease, box-shadow 0.3s ease",
    outline: "none",
    color: "#333333",
    backgroundColor: "#fafafa",
  },
  inputFocus: {
    borderColor: "#4db6ac",
    boxShadow: "0 0 8px rgba(77, 182, 172, 0.5)",
    backgroundColor: "#ffffff",
  },
  button: (loading) => ({
    padding: "14px",
    width: "150px",
    fontSize: "1.1rem",
    fontWeight: "600",
    color: "#ffffff",
    backgroundColor: loading ? "#80cbc4" : "#4db6ac",
    border: "none",
    borderRadius: "8px",
    cursor: loading ? "not-allowed" : "pointer",
    boxShadow: loading ? "none" : "0 4px 12px rgba(77, 182, 172, 0.5)",
    transition: "background-color 0.3s ease, box-shadow 0.3s ease",
    outline: "none",
  }),
  buttonWrapper: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
};
